### ISSUE TITLE
Guard blocks or #pragma once?

### ISSUE THREAD

**Issue by Lensman** [Ericson2314/Voxlap#24]
Just a quick question. I've been using guard blocks, but then I spotted a  comment where you removed a guard block an replaced with #pragma once. Is it okay to continue with guard blocks?

**Comment by Ericson2314** [comment]
Ah was going to mention that. I prefer `#pragma once`. I think it's more efficient and doesn't clutter the name space so double win. If you have a counter argument I'd love to here it though.

**Comment by Lensman** [comment]
Cool.
